---
#Uncomment this if you have separate domain for static files (recommended)
static_domain: http://st1.fornity.com
minify_css: True
minify_js: True

java_path: java
yui_path: tools/yui.jar
closure_path: tools/compiler.jar
#closure_additional_params: --compilation_level ADVANCED_OPTIMIZATIONS
#yui_additional_params: --line-break 0

css_min_dir: static/min/
js_min_dir: static/min/
css_inlined: static/css/inlined.css

js_loader: 
    file: config/minify/loader.js
    name: loader

templates_dir: templates/