---
css_files:
    - css/main.css

js_files:
    - file: js/jquery-1.11.1.js
      name: jquery
    - file: js/application.js
      name: app
      extends:
          - jquery

preload_templates:
    - base.html
    - index.html